In [2]:
import pandas as pd

In [6]:
Kidron2010 = pd.read_csv("../Data/Kidron2010.csv")
Kidron2010.head(5)

,SMILES,Name,MW,MV,PSA,HBD,HBA,HBtot,logP,logD7.0,logD7.4,logD8.0,perm(cm/s),DOI,Unnamed: 14
0,CC(=O)NC1=NN=C(S1)S(=O)(=O)N,acetazolamide,222.3,127,151.7,3,7,10,?0.26,?0.4,?0.55,?0.94,9.100000e-07,10.1021/jm00158a028,NaN
1,CC(C)NCC(COC1=CC=CC=C1CC=C)O,alprenolol,249.3,247,41.5,2,3,5,2.88,0.77,1.13,1.7,2.900000e-05,10.3109/02713689109001766,NaN
2,CC(C)NCC(COC1=CC=C(C=C1)CC(=O)N)O,atenolol,266.3,237,84.6,4,5,9,0.1,?2.02,?1.65,?1.09,6.700000e-07,10.1002/jps.2600721109,NaN
3,C1=CC=C(C=C1)S(=O)(=O)NC2=NN=C(S2)S(=O)(=O)N,benzolamide,320.4,183,177.1,3,8,11,0.2,?1.4,?1.7,?2.11,1.400000e-07,10.1021/jm00158a028,NaN
4,CC1=CC(=CC=C1)OCC(CNCCC2=CC(=C(C=C2)OC)OC)O,bevantolol,345.4,311,60.0,2,5,7,3.38,1.71,2.09,2.62,5.400000e-05,10.1002/jps.2600721109,NaN

In [11]:
Ramsay2018 = pd.read_csv("../Data/Ramsay2018.csv", encoding='unicode_escape')
Ramsay2018.head(5)

,Smiles,Name,Papp (cm/s) * 10^-7,Unnamed: 3
0,CC(=O)NC1=NN=C(S1)S(=O)(=O)N,Acetazolamide,2.27 ± 0.70,NaN
1,CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O...,Ampicillin,1.89 ± 0.24,NaN
2,CC(C)NCC(COC1=CC=C(C=C1)CC(=O)N)O,Atenolol,1.72 ± 0.87,NaN
3,CN1C2CCC1CC(C2)OC(=O)C(CO)C3=CC=CC=C3,Atropine,5.64 ± 2.15,NaN
4,CC1C(C(=O)N1S(=O)(=O)O)NC(=O)C(=NOC(C)(C)C(=O)...,Aztreonam,1.02 ± 0.49,NaN

In [12]:
Ronald1983 = pd.read_csv("../Data/Ronald1983.csv")
Ronald1983.head(5)

,SMILES,Name,"logPt, cm/c",Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,CC(C)(C)NCC(COC1=CC=CC=C1C2CCCC2)O,Penbutolol,-4.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CCC1=CC=CC2=C1OC(=C2)C(CNC(C)(C)C)O,Bufuralol,-4.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CC1=CC(=CC=C1)OCC(CNCCC2=CC(=C(C=C2)OC)OC)O,Bevantolol,-4.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CC(C)NCC(COC1=CC=CC2=CC=CC=C21)O,Propranolol,-4.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CC(C)(C)NCC(COC1=CC=CC2=C1CCCC2=O)O,Levbunolol,-4.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#удалить лишние столбцы

In [ ]:
#привести permeability в один формат

In [ ]:
#поменять название столбика с проницаемостью

In [ ]:
#вставить название статьи и год в виде нового столбца

In [ ]:
#объединить таблицы (smiles, name, permeability, loss, doi, sourse)

In [ ]:
#перевести permeability в формат int или float

In [ ]:
#вывевсти количество строк

In [ ]:
#удалить дубликаты

In [ ]:
#вывести количество строк